apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin
spec:
  type: ClusterIP
  ports:
  - name: phpldapadmin-ui
    port: 9080
    protocol: TCP
    targetPort: 80
  selector:
    app: phpldapadmin
