apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: phpldapadmin
spec:
  to:
    kind: Service
    name: phpldapadmin
    weight: 100
  wildcardPolicy: None
  port:
    targetPort: phpldapadmin-ui
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
