---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: pg-bastudio-db
spec:
  imagePullSecrets:
  - name: ibm-entitlement-key
  instances: 1
  primaryUpdateStrategy: unsupervised
  description: "Postgres for CP4A"
  postgresql:
    parameters:
      ssl_min_protocol_version: TLSv1.2
      max_prepared_transactions: "180"
      max_connections: "225"
  storage:
    storageClass: "ocs-storagecluster-ceph-rbd"
    size: 50Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: px-common-superuser-password
  resources:
    requests:
      memory: "1Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "4"
