oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -c 'create database bastudio;'"
oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -d bastudio -c 'create schema postgres;'"
#oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -c 'create database navdb;'"
#oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -d navdb -c 'create schema postgres;'"
#oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -d navdb -c 'create schema navdb;'"
#oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -c 'create database baspbeng;'"
#oc exec -it pg-bastudio-db-1 -c postgres -- /bin/bash -c "psql -U postgres -d baspbeng -c 'create schema postgres;'"
