apiVersion: zen.cpd.ibm.com/v1
kind: ZenService
metadata:
  name: iaf-zen-cpdservice
spec:
  iamIntegration: true
  scaleConfig: small
  zenCustomRoute:
    route_reencrypt: true 
    route_secret: dummy-tls-cert-1
  fileStorageClass: ocs-external-storagecluster-cephfs
  blockStorageClass: ocs-external-storagecluster-ceph-rbd
