apiVersion: zen.cpd.ibm.com/v1
kind: ZenService
metadata:
  namespace: cp4a
  name: iaf-zen-cpdservice
spec:
  iamIntegration: true
  scaleConfig: small
  zenCustomRoute:
    route_host: #replace with your cpd route hostname
    route_reencrypt: true 
  fileStorageClass: ocs-storagecluster-cephfs
  blockStorageClass: ocs-storagecluster-ceph-rbd
