apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: verify
data: 
  config.yaml: |
    general: 
      ports:
        ldap:  9389

      id: verify

      license:
        key: "R2VuZXJpYzotMToxOjCCAacGCSqGSIb3DQEHAqCCAZgwggGUAgEBMQ8wDQYJYIZIAWUDBAIBBQAwGwYJKoZIhvcNAQcBoA4EDEdlbmVyaWM6LTE6MaAAMYIBXTCCAVkCAQEwSDA8MQswCQYDVQQGEwJ1czEMMAoGA1UEChMDaWJtMQ0wCwYDVQQLEwRpc3ZhMRAwDgYDVQQDEwdzaWduaW5nAgh4PC0gxTSNfzANBglghkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIyMTAxMDA2NTgyN1owLwYJKoZIhvcNAQkEMSIEICNI9qWOUQ1SXQXNbnOMT5HDinpaosSdz13WyWX2XFLiMA0GCSqGSIb3DQEBAQUABIGARibpp/5rnoMDqO9rOSKFwx3m0bbYGgvkiJtDbHcRHTzErgvxqpYV0NLa9CpsCrzySCxiC2v5Xh4XhkalH6IABYWv+ZWRkh1aen8lshEYR1EAgs8llh3FmQ9xRGTJp1XkacRx3XI/s5dNNtWGEqoc1eX3cCXIG9WvO7Uoxc84b+I="
        accept: standard

      admin: 
        dn: cn=root
        pwd: cloudPakPassw0rd!

      audit:
        enabled: true
        failure-only: false
        json-format: false
        log-to-file: true
        operation:
          add: true
          bind: true
          delete: true
          search: true
  
    server:
      replication:
        admin:
          dn: cn=bindUser
          pwd: cloudPakPassw0rd!

      suffixes:
      - dn: dc=cloudpak
        object-classes:
        - domain
        - top
        attributes:
        - dc=cloudpak
        
      change-log:
        enabled: true
        max-days: 56
        max-entries: 99999
        max-hours: 12
