apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ldap-bind-secret
stringData:
  ldapUsername: cn=bindUser
  ldapPassword: cloudPakPassw0rd!
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bas-db-secret
stringData:
  dbUsername: postgres
  dbPassword: password
#---
#apiVersion: v1
#kind: Secret
#type: Opaque
#metadata:
#  name: playback-server-db-secret
#stringData:
#  AE_DATABASE_USER: postgres
#  AE_DATABASE_PWD:  password
#  REDIS_PASSWORD: "password"    
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ibm-ban-secret
stringData:
  navigatorDBUsername: postgres
  navigatorDBPassword: password
  appLoginUsername: icpadmin
  appLoginPassword: cloudPakPassw0rd!
  keystorePassword: cloudPakPassw0rd!
  ltpaPassword: cloudPakPassw0rd!
