apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ldap-bind-secret
stringData:
  ldapUsername: cn=bindUser
  ldapPassword: cloudPakPassw0rd!
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bas-db-secret
stringData:
  dbUsername: postgres
  dbPassword: password
